export const GET_VIDEO_DETAIL_LOADING = 'GET_VIDEO_DETAIL_LOADING';
export const GET_VIDEO_DETAIL_SUCCESS = 'GET_VIDEO_DETAIL_SUCCESS';
export const GET_VIDEO_DETAIL_ERROR = 'GET_VIDEO_DETAIL_ERROR';
